version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 619071308169.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t inetms-gbcd/han-rs .
      - docker tag inetms-gbcd/han-rs:latest 619071308169.dkr.ecr.ap-southeast-1.amazonaws.com/inetms-gbcd/han-rs:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 619071308169.dkr.ecr.ap-southeast-1.amazonaws.com/inetms-gbcd/han-rs:latest
     # - printf '[{"name":"inetms-gbcd-han-cn","imageUri":"619071308169.dkr.ecr.ap-southeast-1.amazonaws.com/inetms-gbcd-han-rs"}]' > imagedefinitions.json
#artifacts:
 # files:
  #  - imagedefinitions.json
