version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 619071308169.dkr.ecr.ap-southeast-1.amazonaws.com || echo "Failed to login to ECR"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t simple-docker-service-0a2a19f577a9 .
      - docker tag simple-docker-service-0a2a19f577a9:latest 619071308169.dkr.ecr.ap-southeast-1.amazonaws.com/simple-docker-service-0a2a19f577a9:latest
      - printf '[{"name":"simple-docker-service-0a2a19f577a9","imageUri":"619071308169.dkr.ecr.ap-southeast-1.amazonaws.com/simple-docker-service-0a2a19f577a9:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
